### ISSUE TITLE
Sabers should not change when in claw mode

### ISSUE THREAD

**Issue by bbarhight** [SteffanDonal/BeatSaber-Claws#9]
Introduced in #8 

# Unwanted behavior

Currently, when claws exposes unspecified behavior in the following scenarios:
## Scenario A:  
_GIVEN_: Claws mode is set
_WHEN_: A saber is selected via the custom sabers menu
_THEN_: The newly selected saber overrides the claws mode saber  

# Desired behavior 

Replace the above scenarios with this behavior. 

## Scenario A:  
_GIVEN_: Claw mode is set
_WHEN_: A new saber is selected via the custom sabers menu
_THEN_: Claws will remain the current saber

**Comment by bbarhight** [comment]
Fixed Scenario B, so I removed it from the issue.

**Comment by SteffanDonal** [comment]
Possible solution:

- On game start, check if mode enabled.
   - If mode enabled, store last saber, set custom saber to claws.
- On game end, if last saber available, set custom saber to last, clear last saber.

I believe this should cover these edge cases pretty well - and reduces the amount of change so that there's "only a state" when playing, where the user cannot change it directly!

**Comment by SteffanDonal** [comment]
Closing - custom saber changing has been completely rewritten and (theoretically 😇) should no longer get stuck in confusing states.

Worse case scenario, sabers will reset back to default on toggling claws.
